spring:
  jpa:
    generate-ddl: 'false'
    database: mysql
    hibernate:
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: create-drop
    show-sql: 'true'
    properties:
      hibernate:
        enable_lazy_load_no_trans: 'true'
        format_sql: 'true'
    database-platform: org.hibernate.dialect.MySQL8Dialect
  security:
    user:
      password: 1234
      name: user
  datasource:
    password: codeclick
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://52.78.10.132:3306/flex?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
logging:
  level:
    root: debug
server:
  port: 8080

jwt:
  secret: Y29kZWNsaWNrX0dNX2Nob1N1bmdXb29fc2hpbmtpeW9lbl9sb3ZlX0ZvcmV2ZXJfWTI5a1pXTnNhV05yWDBkTlgyTm9iMU4xYm1kWGIyOWZjMmhwYm10cGVXOWxibDlzYjNabFgwWnZjbVYyWlhJPV8=